config/routes.rb
Rails.application.routes.draw do
  resources :items
  resources :locations
  resources :wishes
  resources :events
  resources :users
  get '/signup', to: 'users#new', as: 'signup'
  post '/signup', to: 'users#create' 

  get '/login', to: 'auth#login'
  post '/login', to: 'auth#verify'

  get '/logout', to: 'auth#logout'
  
  get '/users/:id/wishlist/:event_id', to: 'users#wishlist'
  get '/users/:id/events', to: 'users#user_events'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
    belongs_to :location
    has_many :wishes
    has_many :users, through: :wishes
    has_many :items, through: :wishes
    validates :dollar_amt_limit, numericality: { greater_than_or_equal_to: 0 }

    def normal_date
        date = self.date.to_s.split("-")
        normal_date = "#{date[1]}/#{date[2]}/#{date[0]}"
    end

end

app/models/item.rb
class Item < ApplicationRecord
    has_many :wishes
end

app/models/location.rb
class Location < ApplicationRecord
    has_many :events

    def full_address
        "#{self.address_1}\n#{self.city}, #{self.state} #{self.zip}"
    end
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password

    has_many :wishes
    has_many :events, through: :wishes
    has_many :items, through: :wishes

    validates :email, presence: true, uniqueness: true

    def event_wishlist(event_id)
        self.wishes.where(event_id: event_id)
    end


    def user_events
        self.events
    end

end

app/models/wish.rb
class Wish < ApplicationRecord
    belongs_to :user
    belongs_to :event
    belongs_to :item
    validates :qty, numericality: { greater_than: 0 }

    def item_name
        self.item.name
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    before_action :redirect_user
    
    helper_method :logged_in?

    def logged_in?
        session[:user_id] == nil ? false : true
    end

    def redirect_user
        if !logged_in?
            redirect_to signup_path
        end
    end

end

app/controllers/auth_controller.rb
class AuthController < ApplicationController
    skip_before_action :redirect_user
    
    def login
    end

    def verify
        @user = User.find_by(email: params[:auth][:email])
        if @user && @user.authenticate(params[:auth][:password])
            session[:user_id] = @user.id
            redirect_to @user
        else
            flash[:message] = "Incorrect login details. Please try again."
            render :login
        end
    end

    def logout
        session[:user_id] = nil
        redirect_to login_path
    end

    def current_user
        @user = User.find(session[:user_id])
    end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController

    def show
        locate_event
    end

    def new
        @event = Event.new
    end

    def create
        @event = Event.new(event_params)
        if @event.save
            redirect_to @event
        else
            render :new
        end
    end

    def edit
        locate_event
    end

    def update
        locate_event
        if @event.update(event_params)
            redirect_to @event
        else
            render :edit
        end
    end

    def destroy
        locate_event
        @event.destroy
        redirect_to "/users/#{session[:user_id]}"
    end

    private

    def locate_event
        @event = Event.find(params[:id])
    end

    def event_params
        params.require(:event).permit(:name, :date, :location_id, :dollar_amt_limit, :description)
    end
    
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    skip_before_action :redirect_user, only:[:new, :create]

    def show
        locate_user
    end

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            redirect_to @user
        else
            render :new
        end
    end

    def edit
        locate_user
    end

    def update
        locate_user
        if @user.update(user_params)
            redirect_to @user
        else
            render :edit
        end
    end

    def wishlist
        # byebug
        locate_user
        @wishlist = @user.event_wishlist(params[:event_id])
    end

    def user_events
        locate_user
        @events = @user.events
    end

    private

    def locate_user
        @user = User.find(params[:id])
    end

    def user_params
        params.require(:user).permit(:name, :email, :password_digest)
    end

    
end

app/controllers/wishes_controller.rb
class WishesController < ApplicationController

    def show
        locate_wish
    end

    def new
        @wish = Wish.new
    end

    def create
        
        @wish = Wish.new(wish_params)
        @wish.user = User.find(session[:user_id])
        if @wish.save
            redirect_to @wish
        else
            render :new
        end
    end

    def edit
        locate_wish
    end

    def update
        locate_wish
        if @wish.update(wish_params)
            redirect_to @wish
        else
            render :edit
        end
    end

    def destroy
        # byebug
        locate_wish
        @wish.destroy
        redirect_to "/users/#{session[:user_id]}/wishlist/#{flash[:event_id]}"
    end

    private

    def locate_wish
        @wish = Wish.find(params[:id])
    end

    def wish_params
        params.require(:wish).permit(:user_id, :event_id, :item_id, :notes, :qty)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/wishes_helper.rb
module WishesHelper
end

app/views/events/edit.html.erb
<h1>Edit Gift Exchange</h1>

<div class="form">
<%= form_for @event do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>
<%= f.label :date %>
<%= f.date_select :date %>
<%= f.label :dollar_amt_limit %>
<%= f.number_field :dollar_amt_limit %>
<%= f.label :description %>
<%= f.text_area :description %>
<%= f.submit %>
<% end %>
</div>

app/views/events/new.html.erb
<h1>Create Gift Exchange</h1>

<div class="form">
<%= form_for @event do |f| %>
<%= f.label :name %>
<%= f.text_field :name %> <br>
<%= f.label :date %>
<%= f.date_select :date %> <br>
<%= f.label "Location" %>
<%= f.collection_select :location_id, Location.all, :id, :city, prompt: true %> <br>
<%= f.label "Gift Price Limit" %>
<%= f.number_field :dollar_amt_limit %> <br>
<%= f.label :description %>
<%= f.text_area :description %> <br>
<%= f.submit %>
<% end %>
</div>

app/views/events/show.html.erb
<h1><%= @event.name %> Gift Exchange</h1>
<br>
<% date = @event.date.to_s.split("-") %>

<h3>When: <%= date[1] %>/<%= date[2] %>/<%= date[0] %></h3>
<h3>Where: <%= @event.location.full_address %></h3>
<h3>Max cost of gift: $<%= @event.dollar_amt_limit %></h3>

<h3>Attendees: </h3>
<ul>
<% @event.users.distinct.each do |user| %>
<li><h5><%= link_to user.name, "/users/#{user.id}/wishlist/#{@event.id}" %></h5></li>
<% end %></ul>
<br><br><br>
<div class="buttons">
<%= button_to "Delete Event", @event, :method => :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GiftExchange2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <nav class="navbar navbar-dark" style="background-color: #DB324D;">
      <a class="navbar-brand" href="/users/<%= session[:user_id] %>"><%= image_tag(asset_path('Giftsterlogo.png'), height: '40')%></a>

      <div class="navbar-nav d-flex flex-row">
        <% if logged_in? %>
        <a class="nav-item nav-link active px-4" href="/users/<%= session[:user_id] %>/events">My Events</a>
        <a class="nav-item nav-link active px-4" href="/wishes/new">Add A Wish</a>
        <a class="nav-item nav-link active px-4" href="/logout">Logout</a>
        <% else %>
        <a class="nav-item nav-link active px-4" href="/login">Login</a>
        <% end %>
      </div>
    </nav>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/edit.html.erb
<h1>Edit Your Profile</h1>

<div class="form">
<%= form_for @user do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>
<%= f.label :email %>
<%= f.text_field :email%>
<%= f.submit %>
<% end %>
</div>

app/views/users/new.html.erb
<h1>Create New User</h1>

<div class="form">
<%= form_for @user do |f| %>
<%= f.label :name %>
<%= f.text_field :name%>
<%= f.label :email %>
<%= f.text_field :email%>
<%= f.label :password %>
<%= f.password_field :password%>
<%= f.label :password_confirmation %>
<%= f.password_field :password_confirmation%>
<%= f.submit %>
<% end %>
</div>

<p>Already have an account? <%= link_to "Log in", login_path %>.</p>

app/views/users/show.html.erb
<h1><%= @user.name %>'s Profile</h1>
<br>
<br>

<div class="d-inline-flex flex-column p-4">
<h3>My Upcoming Gift Exchanges</h3>
<br>
    <ul>
    <% @user.events.distinct.each do |event|%>
        <li><h4><%= link_to event.name, event %></li></h4>
    <% end %>
    </ul>

<% if @user.id == session[:user_id] %>
    <br> 
    <br>
    <div class="buttons">
    <%= button_to "Add Gift Exchange", new_event_path, method: :get %>
    </div>
<% end %><br> <br>
</div>

<div class="d-inline-flex flex-column p-4">
<h3>My Wishlists</h3>
<br>
<ul>
    <% @user.events.distinct.each do |event| %>
        <li><h4><%= link_to event.name, "/users/#{@user.id}/wishlist/#{event.id}" %></h4></li>
    <% end %>
       
</ul>

<% if @user.id == session[:user_id] %>
    <br> 
    <br>
    <div class="buttons">
    <%= button_to "Add Wish", new_wish_path, method: :get %>
    </div>
<% end %><br> <br>
</div>

<% if @user.id == session[:user_id] %>
    <div class="buttons">
    <p><%= button_to "Edit your Profile", edit_user_path, method: :get %></p>
    </div>
<% end %>

app/views/users/user_events.html.erb
<h1>My Gift Exchanges</h1>
<br>
<ul>
<% @user.events.distinct.each do |event| %>
    <li><h4><%= link_to event.name, event %></h4>
       <p><%= event.normal_date %></p>
    </li>
<% end %>
</ul>
<br>
<br>
<div class="buttons">
    <%= button_to "Add Gift Exchange", new_event_path, method: :get %>
</div>

app/views/users/wishlist.html.erb
<% prev_event = Event.find(params[:event_id])%>
<h1> <%= @user.name %>'s Wishlist for <%= prev_event.name %> </h1>
<ul>
<% @wishlist.each do |wish| %>
    <li><%= link_to wish.item.item_name, wish %> <br>
    Quantity: <%= wish.qty %> <br>
    Notes: <%= wish.notes %>
    </li>

<% end %></ul>
<br>
    <div class="buttons">
            <%= button_to "Add Wish", new_wish_path, method: :get %>    
        </div>
        <br>
<div class="buttons">
<%= button_to "#{@user.name}'s Profile", @user, method: :get %>
</div>
<br>
<h4><%= link_to "Return to #{prev_event.name} Gift Exchange", "/events/#{params[:event_id]}" %></h4>

app/views/wishes/edit.html.erb
<h1>Edit Your Wish</h1>

<div class="form">
<%= form_for @wish do |f| %>
<%= f.label "Gift Exchange" %>
<%= f.collection_select :event_id, Event.all, :id, :name, prompt: true %>
<%= f.label "Item" %>
<%= f.collection_select :item_id, Item.all, :id, :item_name, prompt: true %>
<%= f.label :notes %>
<%= f.text_field :notes %>
<%= f.label :qty %>
<%= f.number_field :qty %>
<%= f.submit %>
<% end %>
</div>

app/views/wishes/new.html.erb
<h1>Add a New Wish</h1>
<br>
<div class="form">
<%= form_for @wish do |f| %>
<%= f.label "Gift Exchange" %>
<%= f.collection_select :event_id, Event.all, :id, :name, prompt: true %> <br>
<%= f.label "Item" %>
<%= f.collection_select :item_id, Item.all, :id, :item_name, prompt: true %> <br>
<%= f.label :notes %>
<%= f.text_field :notes %> <br>
<%= f.label :qty %>
<%= f.number_field :qty %> <br> <br>
<%= f.submit %> 
<% end %> 
</div>

app/views/wishes/show.html.erb
<h1><%= @wish.user.name %>'s wish</h1>
<br>
<h3><%= link_to @wish.item.item_name, @wish.item.item_url %></h3>
<h3>Notes: <%= @wish.notes %></h3>
<h3>Quantity: <%= @wish.qty %></h3>
<h3></h3>
<h3><%= link_to "Back to #{@wish.user.name}'s Wishlist", "/users/#{@wish.user_id}/wishlist/#{@wish.event_id}" %></h3>
<br>
<% flash[:event_id] = @wish.event_id%>
<p><%= button_to "Delete Wish", @wish, :method => :delete %></p>
<p><%= button_to "Edit Wish", edit_wish_path, :method => :get %></p>